//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬅️ Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Create preset.
        /// </summary>
        public static string CreatePreset {
            get {
                return ResourceManager.GetString("CreatePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Disable recommendations.
        /// </summary>
        public static string DisableRecommendations {
            get {
                return ResourceManager.GetString("DisableRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👥 Non-unique artists.
        /// </summary>
        public static string DisableUniqueArtists {
            get {
                return ResourceManager.GetString("DisableUniqueArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Enable recommendations.
        /// </summary>
        public static string EnableRecommendations {
            get {
                return ResourceManager.GetString("EnableRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👤 Unique artists.
        /// </summary>
        public static string EnableUniqueArtists {
            get {
                return ResourceManager.GetString("EnableUniqueArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Exclude liked.
        /// </summary>
        public static string ExcludeLikedTracks {
            get {
                return ResourceManager.GetString("ExcludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Exclude playlist.
        /// </summary>
        public static string ExcludePlaylist {
            get {
                return ResourceManager.GetString("ExcludePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Ignore liked.
        /// </summary>
        public static string IgnoreLikedTracks {
            get {
                return ResourceManager.GetString("IgnoreLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Include liked.
        /// </summary>
        public static string IncludeLikedTracks {
            get {
                return ResourceManager.GetString("IncludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Include playlist.
        /// </summary>
        public static string IncludePlaylist {
            get {
                return ResourceManager.GetString("IncludePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗄️ My presets.
        /// </summary>
        public static string MyPresets {
            get {
                return ResourceManager.GetString("MyPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Run preset.
        /// </summary>
        public static string RunPreset {
            get {
                return ResourceManager.GetString("RunPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #️⃣ Set preset size.
        /// </summary>
        public static string SetPresetSize {
            get {
                return ResourceManager.GetString("SetPresetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📩 Target playlist.
        /// </summary>
        public static string TargetPlaylist {
            get {
                return ResourceManager.GetString("TargetPlaylist", resourceCulture);
            }
        }
    }
}
