//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current settings are:
        ///*Include liked tracks* - {0}
        ///*Playlist size* - {1}.
        /// </summary>
        public static string CurrentSettings {
            get {
                return ResourceManager.GetString("CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Exclude liked.
        /// </summary>
        public static string ExcludeLikedTracks {
            get {
                return ResourceManager.GetString("ExcludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎵 Generate playlist.
        /// </summary>
        public static string GeneratePlaylist {
            get {
                return ResourceManager.GetString("GeneratePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Include liked.
        /// </summary>
        public static string IncludeLikedTracks {
            get {
                return ResourceManager.GetString("IncludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Spotify to generate playlist.
        /// </summary>
        public static string LoginToSpotify {
            get {
                return ResourceManager.GetString("LoginToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist size is set!.
        /// </summary>
        public static string PlaylistSizeSet {
            get {
                return ResourceManager.GetString("PlaylistSizeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist size should be lower than 10000!.
        /// </summary>
        public static string PlaylistSizeTooBig {
            get {
                return ResourceManager.GetString("PlaylistSizeTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist size should be greater than 0!.
        /// </summary>
        public static string PlaylistSizeTooSmall {
            get {
                return ResourceManager.GetString("PlaylistSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me new playlist size in reply to this message.
        /// </summary>
        public static string SendPlaylistSize {
            get {
                return ResourceManager.GetString("SendPlaylistSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #️⃣ Set playlist size.
        /// </summary>
        public static string SetPlaylistSize {
            get {
                return ResourceManager.GetString("SetPlaylistSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command data should be positive number indicates playlist size.
        /// </summary>
        public static string WrongPlaylistSize {
            get {
                return ResourceManager.GetString("WrongPlaylistSize", resourceCulture);
            }
        }
    }
}
