//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Create preset.
        /// </summary>
        public static string CreatePreset {
            get {
                return ResourceManager.GetString("CreatePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Exclude liked.
        /// </summary>
        public static string ExcludeLikedTracks {
            get {
                return ResourceManager.GetString("ExcludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Exclude playlist.
        /// </summary>
        public static string ExcludePlaylist {
            get {
                return ResourceManager.GetString("ExcludePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎵 Generate playlist.
        /// </summary>
        public static string GeneratePlaylist {
            get {
                return ResourceManager.GetString("GeneratePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Ignore liked.
        /// </summary>
        public static string IgnoreLikedTracks {
            get {
                return ResourceManager.GetString("IgnoreLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Include liked.
        /// </summary>
        public static string IncludeLikedTracks {
            get {
                return ResourceManager.GetString("IncludeLikedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Include playlist.
        /// </summary>
        public static string IncludePlaylist {
            get {
                return ResourceManager.GetString("IncludePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➖ Liked tracks are excluded.
        /// </summary>
        public static string LikedTracksExcluded {
            get {
                return ResourceManager.GetString("LikedTracksExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Liked tracks are ignored.
        /// </summary>
        public static string LikedTracksIgnored {
            get {
                return ResourceManager.GetString("LikedTracksIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Liked tracks are included.
        /// </summary>
        public static string LikedTracksIncluded {
            get {
                return ResourceManager.GetString("LikedTracksIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Spotify to generate playlist.
        /// </summary>
        public static string LoginToSpotify {
            get {
                return ResourceManager.GetString("LoginToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗄️ My presets.
        /// </summary>
        public static string MyPresets {
            get {
                return ResourceManager.GetString("MyPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse provided playlist id: {0}.
        /// </summary>
        public static string PlaylistIdCannotBeParsed {
            get {
                return ResourceManager.GetString("PlaylistIdCannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to modify this playlist.
        /// </summary>
        public static string PlaylistIsReadonly {
            get {
                return ResourceManager.GetString("PlaylistIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist with id {0} not found is Spotify!.
        /// </summary>
        public static string PlaylistNotFoundInSpotify {
            get {
                return ResourceManager.GetString("PlaylistNotFoundInSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist size is set!.
        /// </summary>
        public static string PlaylistSizeSet {
            get {
                return ResourceManager.GetString("PlaylistSizeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist size should be lower than 10000!.
        /// </summary>
        public static string PlaylistSizeTooBig {
            get {
                return ResourceManager.GetString("PlaylistSizeTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist size should be greater than 0!.
        /// </summary>
        public static string PlaylistSizeTooSmall {
            get {
                return ResourceManager.GetString("PlaylistSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name: *{0}*
        ///Preset settings:
        ///*Include liked tracks* - {1}
        ///*Playlist size* - {2}.
        /// </summary>
        public static string PresetInfo {
            get {
                return ResourceManager.GetString("PresetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send id/url of Spotify playlist to exclude it tracks from generation.
        /// </summary>
        public static string SendExcludedPlaylist {
            get {
                return ResourceManager.GetString("SendExcludedPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send id/url of Spotify playlist to include it tracks into generation.
        /// </summary>
        public static string SendIncludedPlaylist {
            get {
                return ResourceManager.GetString("SendIncludedPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me new playlist size in reply to this message.
        /// </summary>
        public static string SendPlaylistSize {
            get {
                return ResourceManager.GetString("SendPlaylistSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send new preset name in reply to this message.
        /// </summary>
        public static string SendPresetName {
            get {
                return ResourceManager.GetString("SendPresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send id/url of Spotify playlist to save generated tracks into.
        /// </summary>
        public static string SendTargetPlaylist {
            get {
                return ResourceManager.GetString("SendTargetPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #️⃣ Set playlist size.
        /// </summary>
        public static string SetPlaylistSize {
            get {
                return ResourceManager.GetString("SetPlaylistSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📩 Target playlist.
        /// </summary>
        public static string TargetPlaylist {
            get {
                return ResourceManager.GetString("TargetPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command data should be positive number indicates playlist size.
        /// </summary>
        public static string WrongPlaylistSize {
            get {
                return ResourceManager.GetString("WrongPlaylistSize", resourceCulture);
            }
        }
    }
}
